/******************************************************************************************/
/*                               E N T E R   PARAM . H                                                */
/******************************************************************************************/
#ifndef __enterp_h
#define __enterp_h 
  void CreateListFuncKeyPar(void)        ;     
   void TablePar(void);
   void DELCR(void);        
   void NumberCR(void);        
   void NewCR(void);
   void SaveCR(void);
   void TableRight(void);
void TableLeft(void);
void TableBottom(void); 
void TableTop(void);  
void PrintOutputPar(void);
void DrawTablePar(unsigned char);
void DrawPar(void);
#endif                      
